version: '3.8'

services:
  ping-checker:
    build: .
    image: ping-checker:latest
    container_name: ping-checker-daemon
    restart: unless-stopped
    volumes:
      # Mount data directory for persistent storage
      - ./data:/app/data
      # Mount daemon log file to host
      - ./ping_daemon.log:/app/ping_daemon.log
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=UTC
    # Network mode allows container to ping external hosts
    network_mode: bridge
    # Add capabilities needed for ping operations
    cap_add:
      - NET_RAW
    # Optional: Override default command
    # command: ["python", "ping_checker.py", "data/config/sample_ips.txt", "-v"]

    # Optional: Resource limits
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
        reservations:
          memory: 128M
          cpus: '0.25'

  # Optional: One-time ping check service
  ping-checker-oneshot:
    image: ping-checker:latest
    container_name: ping-checker-oneshot
    volumes:
      - ./data:/app/data
    command: ["python", "ping_checker.py", "data/config/sample_ips.txt", "-v"]
    profiles:
      - oneshot  # Only runs when explicitly requested

  # Optional: Log analysis service
  ping-analyzer:
    image: ping-checker:latest
    container_name: ping-analyzer
    volumes:
      - ./data:/app/data
    command: ["python", "analyze_logs.py"]
    profiles:
      - analysis  # Only runs when explicitly requested