services:
  ping-checker:
    build: .
    image: ping-checker:latest
    container_name: ping-checker-daemon
    restart: unless-stopped
    volumes:
      # Mount data directory for persistent storage
      - ./data:/app/data:rw
      # Mount daemon log file to host
      - ./ping_daemon.log:/app/ping_daemon.log:rw
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=UTC
      # Database configuration (optional)
      - DATABASE_URL=${DATABASE_URL:-}
      - DB_HOST=${DB_HOST:-}
      - DB_PORT=${DB_PORT:-}
      - DB_NAME=${DB_NAME:-}
      - DB_USER=${DB_USER:-}
      - DB_PASSWORD=${DB_PASSWORD:-}
      - DB_SCHEMA=${DB_SCHEMA:-}
    # Network mode allows container to ping external hosts
    network_mode: bridge
    # Add capabilities needed for ping operations
    cap_add:
      - NET_RAW
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'